name: Print Repository Secrets

on: 
  push:
    branches:
      - beta

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secrets
        env:
          MY_SECRET_1: ${{ secrets.MY_SECRET_1 }}
        run: |
          echo "Printing repository secrets:"
          echo "MY_SECRET_1: $MY_SECRET_1"
